/**
 * Generated by @openapi-codegen
 *
 * @version 1.0
 */
export type CtfTask = {
  /**
   * @format uuid
   */
  id?: string;
  /**
   * @format date-time
   */
  createdAt: string;
  name?: string | null;
  flag?: string | null;
};
