# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Dotnet Backend Build and Push to DockerHub

on:
  push:
    branches: ["main"]
    paths: ["friByte.capture-the-flag.service/**"]
  pull_request:
    branches: ["main"]
    paths: ["friByte.capture-the-flag.service/**"]

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: friByte/ctf-backend

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./friByte.capture-the-flag.service/
          push: true
          tags: friByte/ctf-backend:latest
